name: ci
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        kind: [test, lint, format]
    steps:
      - name: Clone repository
        uses: actions/checkout@v1

      - name: Install Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.3.1

      - name: Format
        if: matrix.kind == 'format'
        run: deno fmt --check

      - name: Lint
        if: matrix.kind == 'lint'
        run: deno lint --unstable

      - name: Test
        if: matrix.kind == 'test'
        run: deno test --lock lock.json
